### PR TITLE
Feature/pretty printing

### LINKED ISSUE #13: Add pretty printing for feedback
after merging #12  

It would be easier to read if the terms were printed in a human-friendly way

### PR DESCRIPTION
**Pull request by thibautbenjamin**
Because we are not machines

Fix #13

### CODE REVIEW

**Comment by thibautbenjamin** [comment]
@regular-citizen pretty-printing is almost done, but pretty-printing the functorialisations in a reasonable way is not obvious, and requires changing the internal data structure that we use to represent the functorialisation. This change will also let us perform multiple functorialisations at once. I suggest that we do that first and put this MR on hold. Once the refactoring of the functorialisation is done and merged, we can rebase this MR onto it and finish the job

**Comment by regular-citizen** [comment]
> @regular-citizen pretty-printing is almost done, but pretty-printing the functorialisations in a reasonable way is not obvious, and requires changing the internal data structure that we use to represent the functorialisation. This change will also let us perform multiple functorialisations at once. I suggest that we do that first and put this MR on hold. Once the refactoring of the functorialisation is done and merged, we can rebase this MR onto it and finish the job

Seems very sensible, should I still go ahead and review the PR in the meantime?

**Comment by thibautbenjamin** [comment]
Of course. Just don't look at the last 2 commits, as they are nonsense for now

**Comment by thibautbenjamin** [comment]
@regular-citizen after you are done reviewing the refactoring of the functorialisation, you can review this merge request, which does proper pretty-printing. It is likely that there is some more obfuscated/cryptic code in there, so don't hesitate to ask me to add comments when necessary

**Comment by thibautbenjamin** [comment]
@regular-citizen thanks for the rebase :) I have been rebasing the other branches as well

**Pull request merged**
